services:

  frontend:
    image: php:8.2-apache
    container_name: nyvora_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html

  backend:
    image: php:8.2-apache
    container_name: nyvora_backend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql &&
      apache2-foreground
      "

  database:
    image: mysql:8.0
    container_name: nyvora_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nyvora_db
    ports:
      - "3307:3306"
    volumes:
      - nyvora_mysql_data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nyvora_phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - database

volumes:
  nyvora_mysql_data: