"use strict";
document.addEventListener("DOMContentLoaded", () => {
 const search=document.getElementById("medication-search"), statusFilter=document.getElementById("medication-status-filter"), presentationFilter=document.getElementById("medication-presentation-filter"), body=document.getElementById("medications-table-body"), count=document.getElementById("medication-results-count"), modal=document.getElementById("medication-modal"), form=document.getElementById("medication-form");
 const fields={id:null,name:document.getElementById("medication-name"),presentation:document.getElementById("medication-presentation"),concentration:document.getElementById("medication-concentration"),dose:document.getElementById("medication-dose"),frequency:document.getElementById("medication-frequency"),status:document.getElementById("medication-status"),observations:document.getElementById("medication-observations")}; let medications=[];
 const info=(s)=>({ACTIVO:["Activo","active"],EN_USO:["En uso","in-use"],INACTIVO:["Inactivo","inactive"]}[s]||[s,"inactive"]);
 async function load(){const q=new URLSearchParams();if(search.value.trim())q.set("search",search.value.trim());if(statusFilter.value)q.set("status",statusFilter.value);if(presentationFilter.value)q.set("presentation",presentationFilter.value);try{const r=await nyvoraApi(`medications.php?${q}`);medications=r.data||[];render(r.kpis||{});}catch(e){body.innerHTML=`<tr><td colspan="7">${nyvoraEscapeHtml(e.message)}</td></tr>`;}}
 function render(k){[["kpi-medications-total",k.total],["kpi-medications-active",k.active],["kpi-medications-used",k.inUse],["kpi-medications-inactive",k.inactive]].forEach(([id,v])=>document.getElementById(id).textContent=v??0);body.innerHTML="";count.textContent=`${medications.length} ${medications.length===1?"resultado":"resultados"}`;if(!medications.length){body.innerHTML='<tr class="empty-medications"><td colspan="7">No se encontraron medicamentos.</td></tr>';return;}medications.forEach(m=>{const [label,cls]=info(m.status),row=document.createElement("tr");row.innerHTML=`<td><div class="medication-name-cell"><div class="medication-table-icon"><i class="fa-solid fa-capsules"></i></div><div class="medication-name-info"><strong>${nyvoraEscapeHtml(m.name)}</strong><span>${nyvoraEscapeHtml(m.frequency||"Sin frecuencia definida")}</span></div></div></td><td>${nyvoraEscapeHtml(m.presentation)}</td><td>${nyvoraEscapeHtml(m.concentration)}</td><td>${nyvoraEscapeHtml(m.dose||"Sin definir")}</td><td><span class="medication-badge ${cls}">${label}</span></td><td>${m.associatedPatients||0}</td><td><div class="medication-row-actions"><button class="medication-action-button edit" title="Editar"><i class="fa-solid fa-pen"></i></button><button class="medication-action-button disable" title="Dar de baja"><i class="fa-solid fa-ban"></i></button></div></td>`;row.querySelector(".edit").onclick=()=>open(m);row.querySelector(".disable").onclick=()=>deactivate(m);body.appendChild(row);});}
 function open(m){fields.id=m?.id||null;form.reset();document.getElementById("medication-modal-title").textContent=m?"Editar Medicamento":"Registrar Medicamento";["name","presentation","concentration","dose","frequency","status","observations"].forEach(k=>fields[k].value=m?.[k]|| (k==="status"?"ACTIVO":""));modal.classList.add("active");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");}
 function close(){modal.classList.remove("active");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");fields.id=null;}
 async function save(e){e.preventDefault();if(!fields.name.value.trim()||!fields.presentation.value||!fields.concentration.value)return;const data={name:fields.name.value.trim(),presentation:fields.presentation.value,concentration:fields.concentration.value.trim(),dose:fields.dose.value.trim(),frequency:fields.frequency.value.trim(),status:fields.status.value,observations:fields.observations.value.trim()};if(fields.id)data.id=fields.id;try{const r=await nyvoraApi("medications.php",{method:fields.id?"PUT":"POST",body:data});close();nyvoraNotify("medications");await load();alert(r.message);}catch(err){alert(err.message);}}
 async function deactivate(m){if(!confirm(`¿Dar de baja ${m.name}?`))return;try{await nyvoraApi("medications.php",{method:"DELETE",body:{id:m.id}});nyvoraNotify("medications");load();}catch(e){alert(e.message);}}
 [search,statusFilter,presentationFilter].forEach(x=>x.addEventListener(x===search?"input":"change",load));document.getElementById("open-medication-modal").onclick=()=>open();form.onsubmit=save;[document.getElementById("close-medication-modal"),document.getElementById("cancel-medication"),modal.querySelector(".medication-modal-backdrop")].forEach(x=>x.onclick=close);load();
});
